name: firstly
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.3+3

environment:
  sdk: ^3.5.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  confetti: ^0.7.0
  rive: ^0.13.14
  flutter_svg: ^2.0.10+1



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  audioplayers: ^6.1.0
  video_player: ^2.9.2
  google_fonts: ^6.2.1
  just_audio: ^0.9.42

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/iconapp.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/

  - assets/images/iconapp.png

  - assets/images/homepage/kidskubhomepage.png
  - assets/images/homepage/grid.png
  - assets/images/homepage/buttonhome.png
  - assets/images/homepage/buttonplay.png
  - assets/images/homepage/ellipse1.png
  - assets/images/homepage/ellipse2.png
  - assets/images/homepage/line.png
  - assets/images/homepage/polygon1.png
  - assets/images/homepage/polygon2.png
  - assets/images/homepage/rectangle1.png
  - assets/images/homepage/rectangle2.png
  - assets/images/homepage/setting_button.png
  - assets/images/homepage/strickerbook_button.png
  
  - assets/images/strickerbook/receivedbutton.png
  - assets/images/strickerbook/receivedkey.png
  - assets/images/strickerbook/elmstk.png

  - assets/images/strickerbook/book1_left.png
  - assets/images/strickerbook/book1_right.png
  - assets/images/strickerbook/screw.png
  - assets/images/strickerbook/title.png
  - assets/images/strickerbook/title_page1.png
  - assets/images/strickerbook/title_page2.png
  - assets/images/strickerbook/title_page3.png
  - assets/images/strickerbook/title_page4.png
  - assets/images/strickerbook/grid.png
  - assets/images/strickerbook/lock2.png
  - assets/images/strickerbook/lock3.png
  - assets/images/strickerbook/lock4.png
  - assets/images/strickerbook/postcard.png
  - assets/images/strickerbook/postcard_outline.png
  - assets/images/strickerbook/sticker1.png
  - assets/images/strickerbook/sticker1_outline.png
  - assets/images/strickerbook/sticker2.png
  - assets/images/strickerbook/sticker2_outline.png
  - assets/images/strickerbook/sticker3.png
  - assets/images/strickerbook/sticker3_outline.png
  - assets/images/strickerbook/sticker4.png
  - assets/images/strickerbook/sticker4_outline.png
  - assets/images/strickerbook/sticker5.png
  - assets/images/strickerbook/sticker5_outline.png
  - assets/images/strickerbook/sticker6.png
  - assets/images/strickerbook/bg_elm.png

  - assets/images/questionImages/apple.png
  - assets/images/questionImages/blueberry.png
  - assets/images/questionImages/carrot.png
  - assets/images/questionImages/grap.png
  - assets/images/questionImages/lemon.png
  - assets/images/questionImages/mushroom.png
  - assets/images/jarAsset/jarblue.png
  - assets/images/jarAsset/jargreen.png
  - assets/images/jarAsset/jarorange.png
  - assets/images/jarAsset/jarpurple.png
  - assets/images/jarAsset/jarred.png
  - assets/images/jarAsset/jaryellow_1.png

  - assets/images/selectionpage/dotgame.png
  - assets/images/selectionpage/dotgame_lock.png
  - assets/images/selectionpage/linegame.png
  - assets/images/selectionpage/linegame_lock.png
  - assets/images/selectionpage/shapegame.png
  - assets/images/selectionpage/shapegame_lock.png
  - assets/images/selectionpage/colorgame.png
  - assets/images/selectionpage/colorgame_lock.png

  - assets/images/selectionpage/key_bar.png 
  - assets/images/selectionpage/key1.png 
  - assets/images/selectionpage/key1_gray.png
  - assets/images/selectionpage/key2.png 
  - assets/images/selectionpage/key2_gray.png
  - assets/images/selectionpage/key3.png 
  - assets/images/selectionpage/key3_gray.png
  - assets/images/selectionpage/key4_gray.png
  - assets/images/selectionpage/key4.png
  - assets/images/selectionpage/key_notification.png

  - assets/images/selectionpage/color_lock1.png
  - assets/images/selectionpage/color_lock2.png
  - assets/images/selectionpage/dot_lock1.png
  - assets/images/selectionpage/dot_lock2.png
  - assets/images/selectionpage/line_lock1.png
  - assets/images/selectionpage/line_lock2.png
  - assets/images/selectionpage/shape_lock1.png
  - assets/images/selectionpage/shape_lock2.png

  - assets/images/dotchapter/chractor1.png
  - assets/images/dotchapter/bg.png
  - assets/images/dotchapter/elm.png
  - assets/images/dotchapter/lv1_card_lock.png
  - assets/images/dotchapter/lv1_card_unlock.png
  - assets/images/dotchapter/lv2_card_lock.png
  - assets/images/dotchapter/lv2_card_unlock.png
  - assets/images/dotchapter/motion_card.png
  - assets/images/dotchapter/quiz_card_lock.png
  - assets/images/dotchapter/quiz_card_unlock.png
  - assets/images/dotchapter/card3_level.png
  - assets/images/dotchapter/card1_level.png
  - assets/images/dotchapter/card2_level.png
  - assets/images/dotchapter/unlock_notification.png
  

  - assets/images/dotchapter/purple_stars_empty.png 
  - assets/images/dotchapter/purple_stars_full.png 
  - assets/images/dotchapter/yellow_stars_empty.png
  - assets/images/dotchapter/yellow_stars_one.png 
  - assets/images/dotchapter/yellow_stars_two.png 
  - assets/images/dotchapter/yellow_stars_full.png
  - assets/images/dotchapter/purple_stars_0.png
  - assets/images/dotchapter/purple_stars_1.png
  - assets/images/dotchapter/yellow_stars_0.png
  - assets/images/dotchapter/yellow_stars_1.png
  - assets/images/dotchapter/yellow_stars_2.png
  - assets/images/dotchapter/yellow_stars_3.png
  - assets/images/dotchapter/yellow_stars_4.png
  - assets/images/dotchapter/yellow_stars_5.png

  - assets/images/dotgame_easy/watermelon_bottom.png
  - assets/images/dotgame_easy/watermelon_top.png
  - assets/images/dotgame_easy/watermelon_middle.png
  - assets/images/dotgame_easy/watermelon.png
  - assets/images/dotgame_easy/board.png
  - assets/images/dotgame_easy/plate.png
  - assets/images/dotgame_easy/watermelon2.png
  - assets/images/dotgame_easy/watermelon2_1.png
  - assets/images/dotgame_easy/watermelon2_2.png
  - assets/images/dotgame_easy/watermelon2_3.png
  - assets/images/dotgame_easy/watermelon2_4.png
  - assets/images/dotgame_easy/watermelon3.png

  - assets/images/dotgamehard/bgscreen.png
  - assets/images/dotgamehard/clock.png
  - assets/images/dotgamehard/bgpopup.png
  - assets/images/dotgamehard/bgprocress.png

  - assets/images/quizdot/bar.png
  - assets/images/quizdot/transparent_overlay.png
  - assets/images/quizdot/bg_elm.png
  - assets/images/quizdot/dice_1.png
  - assets/images/quizdot/dice_2.png
  - assets/images/quizdot/dice_3.png
  - assets/images/quizdot/dice_4.png
  - assets/images/quizdot/dice_5.png
  - assets/images/quizdot/dice_6.png
  - assets/images/quizdot/dice_answers.png
  - assets/images/quizdot/dice_400.png
  - assets/images/quizdot/dice_900.png
  - assets/images/quizdot/dice_40.png
  - assets/images/quizdot/dice_50.png
  - assets/images/quizdot/dice_42.png
  - assets/images/quizdot/dice_240.png
  - assets/images/quizdot/dice_250.png
  - assets/images/quizdot/dice_260.png
  - assets/images/quizdot/dice_270.png
  - assets/images/quizdot/empty_heart.png
  - assets/images/quizdot/full_heart.png
  - assets/images/quizdot/question_4.png
  - assets/images/quizdot/question_5.png
  - assets/images/quizdot/question_6.png
  - assets/images/quizdot/pattern_answers.png
  - assets/images/quizdot/bg_grid_quizdot.png
  - assets/images/quizdot/send.png
  - assets/images/quizdot/hearts_bg.png

  - assets/images/result/back.png
  - assets/images/result/character1.png
  - assets/images/result/character2.png
  - assets/images/result/light1.png
  - assets/images/result/light2.png
  - assets/images/result/next.png
  - assets/images/result/overlay_black.png
  - assets/images/result/playagain.png
  - assets/images/result/playagain2.png
  - assets/images/result/stage1.png
  - assets/images/result/stage2.png
  - assets/images/result/star0.png
  - assets/images/result/star1.png
  - assets/images/result/star2.png
  - assets/images/result/star3.png
  - assets/images/result/stage_purple.png
  - assets/images/result/star_purple1.png
  - assets/images/result/next_purple.png
  - assets/images/result/playagain_purple.png
  - assets/images/result/light_purple.png
  - assets/images/result/star_purple0.png
  
  - assets/images/Hint3.png
  - assets/images/Hint4.png
  - assets/images/HintButton.png
  - assets/images/Hint1.png
  - assets/images/Hint2.png
  - assets/quiz1.riv
  - assets/images/comingsoon.png
  - assets/images/line.png
  - assets/images/starempty.png
  - assets/images/starfull.png

  - assets/motion/Scene1.mp4
  - assets/motion/Scene2.mp4
  - assets/motion/Scene3.mp4
  - assets/motion/Scene4.mp4
  - assets/motion/Scene5.mp4
  - assets/motion/Scene6.mp4
  - assets/motion/Scene7.mp4
  - assets/motion/Scene8.mp4

  - assets/images/setting/bar.png
  - assets/images/setting/button_minus.png
  - assets/images/setting/button_plus.png
  - assets/images/setting/music_icon.png
  - assets/images/setting/sfx_icon.png
  - assets/images/setting/exit.png

  - assets/music/background_music.mp3
  - assets/music/click_sound.mp3

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
